[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
blur = false
title = "Terminal"
dynamic_title = true
decorations = "None"

[font]
normal = {family = "Monaspace Xenon", style = "Regular"}
size = 10

[cursor]
style = {shape = "Underline", blinking="Never"}

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = false
cursor = {
  text = "#55cdfc",
  cursor = "#a96cf2"
}
