[window]
blur = true
title = "Terminal"
dynamic_title = true
decorations = "None"

[font]
normal = {family = "Monaspace Xenon", style = "Regular"}
size = 10

[cursor]
style = {shape = "Underline", blinking="Never"}

[mouse]
hide_when_typing = true
