#!/usr/bin/bash
export RESTIC_REPOSITORY=/mnt/nas/share/backups
export RESTIC_PASSWORD="secrets"
clean_dev
restic backup --one-file-system /
restic backup $HOME --exclude $HOME/Documents/exclude --exclude-caches
