#!/usr/bin/bash
export RESTIC_REPOSITORY=/mnt/nas/share/backups
export RESTIC_PASSWORD="secrets"
clean_dev
restic backup --one-file-system --skip-if-unchanged --exclude-caches /
restic backup $HOME --exclude $HOME/Documents/exclude --exclude-caches
restic forget --keep-daily 7
