#!/usr/bin/bash
mkdir -p /home/charlotte/usb/password
cp /home/charlotte/Documents/docsoff/password/Passwords.kdbx /home/charlotte/usb/password/.
echo "Passwords saved at $(date +%Y-%m-%d#%H:%M)" >> /home/charlotte/.passwords.log
