#!/usr/bin/bash
clean_dev

set -o errexit
set -o nounset
set -o pipefail

readonly BACKUP_DIR="/home/charlotte/usb/backups"
readonly DATETIME="$(date +%Y-%m-%d_%H:%M:%S)"
readonly SOURCE_DIR="/"
readonly BACKUP_PATH="${BACKUP_DIR}/${DATETIME}"
readonly LATEST_LINK="${BACKUP_DIR}/latest"

mkdir -p "${BACKUP_DIR}"
mkdir -p "${BACKUP_PATH}"

echo "Starting backup of ${SOURCE_DIR} to ${BACKUP_PATH}"

rsync -avz --delete \
	"${SOURCE_DIR}/" \
	--link-dest "${LATEST_LINK}" \
	--exclude='.git/' \
	"${BACKUP_PATH}"

rm -rf "${LATEST_LINK}"
ln -s "${BACKUP_PATH}" "${LATEST_LINK}"
