#!/usr/bin/bash
clean_dev

set -o errexit
set -o nounset
set -o pipefail

readonly SOURCE_DIR_DEV="${HOME}/Documents/dev"
readonly SOURCE_DIR_DOCSOFF="${HOME}/Documents/docsoff"
readonly BACKUP_DIR="${HOME}/usb"
readonly DATETIME="$(date +%Y-%m-%d_%H:%M:%S)"
readonly BACKUP_PATH_DEV="${BACKUP_DIR}/dev/${DATETIME}"
readonly LATEST_LINK_DEV="${BACKUP_DIR}/dev/latest"
readonly BACKUP_PATH_DOCSOFF="${BACKUP_DIR}/docsoff/${DATETIME}"
readonly LATEST_LINK_DOCSOFF="${BACKUP_DIR}/docsoff/latest"

mkdir -p "${BACKUP_DIR}"
mkdir -p "${BACKUP_PATH_DOCSOFF}"
mkdir -p "${BACKUP_PATH_DEV}"

echo "Starting backup of ${SOURCE_DIR_DEV} to ${BACKUP_PATH_DEV}"

rsync -avz --delete \
	"${SOURCE_DIR_DEV}/" \
	--link-dest "${LATEST_LINK_DEV}" \
	--exclude='.git/' \
	"${BACKUP_PATH_DEV}"

rm -rf "${LATEST_LINK_DEV}"
ln -s "${BACKUP_PATH_DEV}" "${LATEST_LINK_DEV}"

echo "Starting backup of ${SOURCE_DIR_DOCSOFF} to ${BACKUP_PATH_DOCSOFF}"

rsync -av --delete \
	"${SOURCE_DIR_DOCSOFF}/" \
	--link-dest "${LATEST_LINK_DOCSOFF}" \
	--exclude='.git/' \
	"${BACKUP_PATH_DOCSOFF}"

rm -rf "${LATEST_LINK_DOCSOFF}"
ln -s "${BACKUP_PATH_DOCSOFF}" "${LATEST_LINK_DOCSOFF}"

echo "Backup finished for ${DATETIME}"
echo "backup done at $(date +%Y-%m-%d#%H:%M)" >> /home/charlotte/.nas_backup.log
