#!/usr/bin/python3
from dotenv import load_dotenv
import os
import smtplib
import ssl

load_dotenv()
email=os.getenv("USERNAME")
password=os.getenv("PASSWORD")
send=os.getenv("SEND")
message = ""
with open("/home/charlotte/report.html","r") as file:
    message = file.read()

# Create a secure SSL context
context = ssl.create_default_context()

with smtplib.SMTP_SSL("smtp.migadu.com", 465, context=context) as server:
    server.login(email, password)
    server.sendmail(email,send,message)

with open("/home/charlotte/report.html","w") as file:
    file.write("Subject: Science Division Monthly Report \nFrom: Charlotte Thomas \n \n")
