#!/usr/bin/bash
file="/sys/class/power_supply/hid-34:f6:8d:f1:77:0c-battery/capacity"
if [[ ! -e $file ]]; then 
	exit 1;
fi 
capacity=$(timeout 1s cat $file)
output=$"{\"text\":\"$capacity\",\"tooltip\":true,\"tooltip-format\":\"Battery {percentage}%\",\"format\":\"\",\"percentage\":$capacity,\"class\":\"test\"}"
echo $output
exit 127;

