swipe:
  3:
    down:
      sendkey: LEFTMETA+LEFTCTRL+S
  4:
    left:
      command: "rofi-bluetooth"
    right:
      command: 'alacritty -e fish -c "nvim"'
pinch:
  in:
    sendkey: LEFTCTRL+KPPLUS
  out:
    sendkey: LEFTCTRL+KPMINUS
threshold:
  swipe: 0.5
  pinch: 0.2
interval:
  swipe: 0.2
  pinch: 0.6
